# Generated by Django 5.2.1 on 2025-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='execution_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='password',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='unlocked_file',
            field=models.FileField(blank=True, null=True, upload_to='unlocked_pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='locked_pdfs/'),
        ),
    ]
