# Generated by Django 5.2.1 on 2025-05-10 14:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_upload', '0002_pdffile_attempts_pdffile_execution_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\temp_unlock_pdf'), upload_to='locked_pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='unlocked_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='C:\\temp_unlock_pdf'), upload_to='unlocked_pdfs/'),
        ),
    ]
