# Generated by Django 5.2.1 on 2025-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_upload', '0003_alter_pdffile_file_alter_pdffile_unlocked_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='digits',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='locked_pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='unlocked_file',
            field=models.FileField(blank=True, null=True, upload_to='unlocked_pdfs/'),
        ),
    ]
